[project]
name = "choice-stopping"
version = "0.1.0"
description = "Task for WP2 of ReTune B03 2nd funding period."
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["numpy>=2.1.2", "psychopy>=2024.1.4"]
